# Generated by Django 4.1.4 on 2023-10-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweetsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tags', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('tweet', models.TextField()),
                ('reply', models.TextField()),
                ('retweets', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
