# Generated by Django 4.1.4 on 2023-10-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_tweetsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetsdata',
            name='likes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tweetsdata',
            name='retweets',
            field=models.CharField(max_length=255),
        ),
    ]
